### ISSUE TITLE
这个加到plugins下似乎不会被识别啊

### ISSUE THREAD

**Issue by aillear** [AreCie/Apex_Tool#1]
按照readme上操作了,重启了好几次都不会被识别

**Comment by AreCie** [comment]
> 按照readme上操作了,重启了好几次都不会被识别

启动时的加载列表中有出现这个插件名“Apex_Tool”么？

**Comment by aillear** [comment]
> > 按照readme上操作了,重启了好几次都不会被识别
> 
> 启动时的加载列表中有出现这个插件名“Apex_Tool”么？

没

**Comment by AreCie** [comment]
> > > 按照readme上操作了,重启了好几次都不会被识别
> > 
> > 
> > 启动时的加载列表中有出现这个插件名“Apex_Tool”么？
> 
> 没

啊这....要不日志列表还有插件目录列表截个图我看看？

**Comment by aillear** [comment]
![图片](https://user-images.githubusercontent.com/91419191/171617922-a0df962e-a478-45ce-860a-29986d7c5c71.png)
![图片](https://user-images.githubusercontent.com/91419191/171618157-ac4befcc-2574-41c1-87af-6e13d4ab40cf.png)
这个吗?

**Comment by AreCie** [comment]
> 

> ![图片](https://user-images.githubusercontent.com/91419191/171617922-a0df962e-a478-45ce-860a-29986d7c5c71.png) ![图片](https://user-images.githubusercontent.com/91419191/171618157-ac4befcc-2574-41c1-87af-6e13d4ab40cf.png) 这个吗?

啊这...要不你把文件夹名字改成【Apex_Tool】试试？我现在在地铁上，你的环境是Ubuntu吧，等到家了我整个新环境试试

**Comment by aillear** [comment]
> 

去掉数字就好起来了!!感谢大佬 :)

**Comment by AreCie** [comment]
> > 
> 
> 去掉数字就好起来了!!感谢大佬 :)

这个【-1.0】是为了规范好区分，加的版本号，没想到成BUG了，等下我改下(⁄ ⁄•⁄ω⁄•⁄ ⁄)
