### ISSUE TITLE
显示api请求错误

### ISSUE THREAD

**Issue by LSGLSH** [AreCie/Apex_Tool#11]
没有其他报错就一个显示api请求错误，

**Comment by AreCie** [comment]
请提供日志信息或日志截图

**Comment by akua0z** [comment]
> 没有其他报错就一个显示api请求错误，

我也碰到了这个情况,有可能是id错误，没有该账号的信息，你看看bot运行的时候返回状态是不是404

**Comment by akua0z** [comment]
> 请提供日志信息或日志截图

大大我想问一下，就是查询网站里api默认是2秒一次。上面说通过绑定disc可以升级为1秒2次，但是为啥点击绑定授权后显示已经关联。但是再刷新（或者重新打开查询网站）又会显示你没有授权绑定。明明disc上已经显示授权了，速率还是没变。

**Comment by AreCie** [comment]
> > 请提供日志信息或日志截图
> 
> 大大我想问一下，就是查询网站里api默认是2秒一次。上面说通过绑定disc可以升级为1秒2次，但是为啥点击绑定授权后显示已经关联。但是再刷新（或者重新打开查询网站）又会显示你没有授权绑定。明明迪斯上已经显示授权了，速率还是没变。

我当时认证时用密钥登陆接口网站后，去授权认证disc完就行了，没有出现你这种情况；授权认证的密钥记得和使用的是同一个；速率我试验过，同时运行两个Bot，认证之前执行命令，必有一个会出现频繁请求类似的信息，认证后再去同时执行命令，两个都会请求成功

**Comment by akua0z** [comment]
> 

感谢大大的回复，我流程倒是和你一样的，用密钥登陆，然后点击授权。就是关闭网站后重新，打开又会回到未授权的状态。我再去多试试
