### ISSUE TITLE
请求API 出错 

### ISSUE THREAD

**Issue by Evilshadowruin** [AreCie/Apex_Tool#12]
10-04 11:41:18 [INFO] nonebot | Event will be handled by <Matcher from plugins.Apex_Tool, type=message, priority=5, temp=False>
10-04 11:41:19 [INFO] plugins | 请求https://api.mozambiquehe.re/maprotation?auth=4d532a88e14a91d2ad4ee0ae48707a0e&version=1时返回的状态码:【404】
10-04 11:41:19 [INFO] nonebot | Matcher <Matcher from plugins.Apex_Tool, type=message, priority=5, temp=False> running complete
10-04 11:41:25 [SUCCESS] nonebot | ONEBOT V11 3176972112 | [message.private.friend]: Message -289580393 from 1979318585 "a猎杀"
10-04 11:41:25 [INFO] nonebot | Event will be handled by <Matcher from plugins.mute, type=message, priority=1, temp=False>
10-04 11:41:25 [INFO] nonebot | Event will be handled by <Matcher from plugins.black_word, type=message, priority=1, temp=False>
10-04 11:41:25 [INFO] nonebot | Event will be handled by <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False>
10-04 11:41:25 [INFO] nonebot | Matcher <Matcher from plugins.mute, type=message, priority=1, temp=False> running complete
10-04 11:41:25 [INFO] nonebot | Matcher <Matcher from plugins.black_word, type=message, priority=1, temp=False> running complete
10-04 11:41:25 [INFO] nonebot | Matcher <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False> running complete
10-04 11:41:25 [INFO] nonebot | Event will be handled by <Matcher from plugins.Apex_Tool, type=message, priority=5, temp=False>
10-04 11:41:26 [INFO] plugins | 请求https://api.mozambiquehe.re/predator?auth=4d532a88e14a91d2ad4ee0ae48707a0e时返回的状态码:【404】
10-04 11:41:26 [INFO] nonebot | Matcher <Matcher from plugins.Apex_Tool, type=message, priority=5, temp=False> running complete

状态404

**Comment by AreCie** [comment]
如果说是插件正常，日志里返回状态码404，那就不用管，官方有定义状态码的信息：<html>
<body>
<p style="margin-right: 1156px; padding: 0px 28px; box-sizing: border-box; display: block; line-height: 1.6; margin-top: 0px; color: rgb(51, 51, 51); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(243, 247, 249); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">The API uses the following error codes:</p>

Error Code | Meaning
-- | --
400 | Try again in a few minutes.
403 | Unauthorized / Unknown API key.
404 | The player could not be found.
405 | External API error.
410 | Unknown platform provided.
429 | Rate limit reached.
500 | Internal error.


</body>
</html>

不过我看了下你这个请求链接，返回信息是``Error: API key doesn't exist !``，意思是你这个API密钥不存在，所以你可以检查下你的密钥是否在配置文件中填写错误

**Comment by Evilshadowruin** [comment]
\zhenxun_bot-main\plugins\Apex_Tool  目录下 config 
# API Token
Tool_Token = "4d532a88e14a91d2ad4ee0ae48707a0e"
# 此插件根目录
Tool_Path = os.path.dirname(__file__)


关联成功
帐户user-lyf#4661已与您的 API 密钥4d532a88e14a91d2ad4ee0ae48707a0e 关联。您的速率限制现已恢复正常。（访问类型 = ）
我核查过API秘钥并没有输入错误 不知道是遗漏了什么？

**Comment by Evilshadowruin** [comment]
> 如果说是插件正常，日志里返回状态码404，那就不用管，官方有定义状态码的信息：
> 
> The API uses the following error codes:
> 
> Error Code	Meaning
> 400	Try again in a few minutes.
> 403	Unauthorized / Unknown API key.
> 404	The player could not be found.
> 405	External API error.
> 410	Unknown platform provided.
> 429	Rate limit reached.
> 500	Internal error.
> 不过我看了下你这个请求链接，返回信息是，意思是你这个API密钥不存在，所以你可以检查下你的密钥是否在配置文件中填写错误`Error: API key doesn't exist !`



> 如果说是插件正常，日志里返回状态码404，那就不用管，官方有定义状态码的信息：
> 
> The API uses the following error codes:
> 
> Error Code	Meaning
> 400	Try again in a few minutes.
> 403	Unauthorized / Unknown API key.
> 404	The player could not be found.
> 405	External API error.
> 410	Unknown platform provided.
> 429	Rate limit reached.
> 500	Internal error.
> 不过我看了下你这个请求链接，返回信息是，意思是你这个API密钥不存在，所以你可以检查下你的密钥是否在配置文件中填写错误`Error: API key doesn't exist !`

# API Token
Tool_Token = "4d532a88e14a91d2ad4ee0ae48707a0e"

# 此插件根目录
Tool_Path = os.path.dirname(__file__)

**Comment by AreCie** [comment]
此密钥确实存在问题，你可以重新申请一个试试

**Comment by Evilshadowruin** [comment]
> 



> 此密钥确实存在问题，你可以重新申请一个试试

很奇怪我重新尝试申请了一个但是依旧还是一样的报错 
生成的API秘钥就像没办法正常使用一样 验证也是不存在

**Comment by Evilshadowruin** [comment]
> 此密钥确实存在问题，你可以重新申请一个试试

当我第四次尝试申请API的时候 新的密钥可以正常访问了，这很无奈，应该是API这边的问题。
