### ISSUE TITLE
两个重复的函数

### ISSUE THREAD

**Issue by SnowWarri0r** [AreCie/Apex_Tool#13]
https://github.com/AreCie/Apex_Tool/blob/11b3e90bbe23566c022a320092fb56b8291b382e/utils.py#L70

**Comment by AreCie** [comment]
> https://github.com/AreCie/Apex_Tool/blob/11b3e90bbe23566c022a320092fb56b8291b382e/utils.py#L70

已删除，感谢提醒，应该是不小心多粘了一份(*/ω＼*)

**Comment by SnowWarri0r** [comment]
我刚好昨天翻到这个插件，然后就正在改写接入自己的bot，无意中瞄到q(≧▽≦q)

**Comment by AreCie** [comment]
> 我刚好昨天翻到这个插件，然后就正在改写接入自己的bot，无意中瞄到q(≧▽≦q)

感谢，翻了下提交记录，应该是最开始加上压缩图片的时候，多复制的≡(▔﹏▔)≡
