### ISSUE TITLE
关于__init__文件import State的报错

### ISSUE THREAD

**Issue by 4Nanai** [AreCie/Apex_Tool#14]
init文件中
from nonebot.params import State, CommandArg, ArgStr
启动时报错param.py中并没有State这个module，我把import State改成import StateParam后启动使用没有问题。想问问这里是不是module名字改了没有更新？

**Comment by AreCie** [comment]
> init文件中 from nonebot.params import State, CommandArg, ArgStr 启动时报错param.py中并没有State这个module，我把import State改成import StateParam后启动使用没有问题。想问问这里是不是module名字改了没有更新？

目前新版本确实还没测试，稍后我更新下新版本测试下，感谢反馈

**Comment by AreCie** [comment]
最新代码已提交，直接覆盖``__init__.py``文件即可
