### ISSUE TITLE
插件重新下载放入后报错

### ISSUE THREAD

**Issue by akua0z** [AreCie/Apex_Tool#15]
![_5T%3618XF9W}RE3A(UTV}7](https://user-images.githubusercontent.com/113225788/197215625-912de18c-5d32-4c64-b824-53a664b93c3b.png)

一不小心把插件删了，然后重新下载放进去之后，重启BOT就这样了

**Comment by AreCie** [comment]
已修复，最新代码已提交，直接覆盖``__init__.py``文件即可
