### ISSUE TITLE
载入时报错 ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by Otakusprpr** [AreCie/Apex_Tool#2]
大佬你好，我在安装这个插件的时候发现插件载入失败，使用的是Windows Server 2012 R2，尝试过pip install requests显示已安装，pip list里也能看到requests，因为没有相关基础实在琢磨不懂了，大佬可以帮忙看看吗？

06-04 14:12:36 [ERROR] nonebot | Failed to import "Apex_Tool"
Traceback (most recent call last):

  File "C:\Users\Administrator\Desktop\zhenxun_bot-main\zhenxun_bot-main\bot.py", line 14, in <module>
    nonebot.load_plugins("plugins")
    │       └ <function load_plugins at 0x00000013496F7DC0>
    └ <module 'nonebot' from 'C:\\Users\\Administrator\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\zhenxun-bot--1-ZcKUM-py3.9\\l...

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot--1-ZcKUM-py3.9\lib\site-packages\nonebot\plugin\load.py", line 39, in load_plugins
    return manager.load_all_plugins()
           │       └ <function PluginManager.load_all_plugins at 0x00000013496F29D0>
           └ <nonebot.plugin.manager.PluginManager object at 0x000000134ACA6EE0>

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot--1-ZcKUM-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 128, in load_all_plugins
    return set(

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot--1-ZcKUM-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 129, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.list_plugins()))
                  │    │           │         │       │    └ <function PluginManager.list_plugins at 0x00000013496F28B0>
                  │    │           │         │       └ <nonebot.plugin.manager.PluginManager object at 0x000000134ACA6EE0>
                  │    │           │         └ 'Apex_Tool'
                  │    │           └ 'Apex_Tool'
                  │    └ <function PluginManager.load_plugin at 0x00000013496F2940>
                  └ <nonebot.plugin.manager.PluginManager object at 0x000000134ACA6EE0>

> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot--1-ZcKUM-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 106, in load_plugin
    module = importlib.import_module(
             │         └ <function import_module at 0x00000013469DB160>
             └ <module 'importlib' from 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\lib\\importlib\\__init__.py'>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'plugins.Apex_Tool'
           │          └ <function _gcd_import at 0x00000013465813A0>
           └ <module 'importlib._bootstrap' (frozen)>

  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot--1-ZcKUM-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 194, in exec_module
    super().exec_module(module)
                        └ <module 'plugins.Apex_Tool' from 'C:\\Users\\Administrator\\Desktop\\zhenxun_bot-main\\zhenxun_bot-main\\plugins\\Apex_Tool\\...

  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed

  File "C:\Users\Administrator\Desktop\zhenxun_bot-main\zhenxun_bot-main\plugins\Apex_Tool\__init__.py", line 11, in <module>
    from .utils import *

  File "C:\Users\Administrator\Desktop\zhenxun_bot-main\zhenxun_bot-main\plugins\Apex_Tool\utils.py", line 1, in <module>
    import requests

ModuleNotFoundError: No module named 'requests'

**Comment by AreCie** [comment]
> 大佬你好，我在安装这个插件的时候发现插件载入失败，使用的是Windows Server 2012 R2，尝试过pip install requests显示已安装，pip list里也能看到requests，因为没有相关基础实在琢磨不懂了，大佬可以帮忙看看吗？
> 
> 06-04 14:12:36 [ERROR] nonebot | Failed to import "Apex_Tool" Traceback (most recent call last):
> 
> File "C:\Users\Administrator\Desktop\zhenxun_bot-main\zhenxun_bot-main\bot.py", line 14, in nonebot.load_plugins("plugins") │ └ <function load_plugins at 0x00000013496F7DC0> └ <module 'nonebot' from 'C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot--1-ZcKUM-py3.9\l...
> 
> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot--1-ZcKUM-py3.9\lib\site-packages\nonebot\plugin\load.py", line 39, in load_plugins return manager.load_all_plugins() │ └ <function PluginManager.load_all_plugins at 0x00000013496F29D0> └ <nonebot.plugin.manager.PluginManager object at 0x000000134ACA6EE0>
> 
> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot--1-ZcKUM-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 128, in load_all_plugins return set(
> 
> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot--1-ZcKUM-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 129, in filter(None, (self.load_plugin(name) for name in self.list_plugins())) │ │ │ │ │ └ <function PluginManager.list_plugins at 0x00000013496F28B0> │ │ │ │ └ <nonebot.plugin.manager.PluginManager object at 0x000000134ACA6EE0> │ │ │ └ 'Apex_Tool' │ │ └ 'Apex_Tool' │ └ <function PluginManager.load_plugin at 0x00000013496F2940> └ <nonebot.plugin.manager.PluginManager object at 0x000000134ACA6EE0>
> 
> > File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot--1-ZcKUM-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 106, in load_plugin
> > module = importlib.import_module(
> > │         └ <function import_module at 0x00000013469DB160>
> > └ <module 'importlib' from 'C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\importlib\**init**.py'>
> 
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\importlib__init__.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) │ │ │ │ │ └ 0 │ │ │ │ └ None │ │ │ └ 0 │ │ └ 'plugins.Apex_Tool' │ └ <function _gcd_import at 0x00000013465813A0> └ <module 'importlib._bootstrap' (frozen)>
> 
> File "", line 1030, in _gcd_import File "", line 1007, in _find_and_load File "", line 986, in _find_and_load_unlocked File "", line 680, in _load_unlocked
> 
> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot--1-ZcKUM-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 194, in exec_module super().exec_module(module) └ <module 'plugins.Apex_Tool' from 'C:\Users\Administrator\Desktop\zhenxun_bot-main\zhenxun_bot-main\plugins\Apex_Tool\...
> 
> File "", line 850, in exec_module File "", line 228, in _call_with_frames_removed
> 
> File "C:\Users\Administrator\Desktop\zhenxun_bot-main\zhenxun_bot-main\plugins\Apex_Tool__init__.py", line 11, in from .utils import *
> 
> File "C:\Users\Administrator\Desktop\zhenxun_bot-main\zhenxun_bot-main\plugins\Apex_Tool\utils.py", line 1, in import requests
> 
> ModuleNotFoundError: No module named 'requests'

没有【requests】这个模块，安装下就行
pip install requests

**Comment by Otakusprpr** [comment]
> 

感谢大佬回复！
![image](https://user-images.githubusercontent.com/106815793/171987847-459784cc-706a-4a2b-9060-4c34f774dd50.png)
但是很奇怪，我尝试pip install request也显示已安装，pip list里也有，但就是在载入的时候报错，很不解
![image](https://user-images.githubusercontent.com/106815793/171987887-96db4b51-8945-40fb-9749-4ee4481109d1.png)

**Comment by AreCie** [comment]
> > 
> 
> 感谢大佬回复！ ![image](https://user-images.githubusercontent.com/106815793/171987847-459784cc-706a-4a2b-9060-4c34f774dd50.png) 但是很奇怪，我尝试pip install request也显示已安装，pip list里也有，但就是在载入的时候报错，很不解 ![image](https://user-images.githubusercontent.com/106815793/171987887-96db4b51-8945-40fb-9749-4ee4481109d1.png)

在虚拟环境里安装，就是poetry shell里面，之前我也遇到过

**Comment by Otakusprpr** [comment]
> 

万分感谢！刚刚跑起来了，的确要在poetry shell里安装，谢谢大佬！

**Comment by AreCie** [comment]
1
