### ISSUE TITLE
希望能添加追踪器汉化 及为什么新英雄没图片

### ISSUE THREAD

**Issue by quanquan1014** [AreCie/Apex_Tool#3]
<img width="145" alt="image" src="https://user-images.githubusercontent.com/69108232/172033967-efa5a903-07b2-4f07-91e4-3408a52d811b.png">

**Comment by AreCie** [comment]
> <img alt="image" width="145" src="https://user-images.githubusercontent.com/69108232/172033967-efa5a903-07b2-4f07-91e4-3408a52d811b.png">

OK，追踪器下周日之前加上，关于新传奇图片，因为调用的是接口，接口里没有新英雄的图片，所以....诶嘿_§:з)))」∠)_

**Comment by quanquan1014** [comment]
催更

**Comment by AreCie** [comment]
> 催更

收到！😣

**Comment by AreCie** [comment]
已汉化，不过是1.0，因为我的派派号没几个追踪器，这些有部分是我按照其英文对照过来的，如果有未汉化或者翻译错误的，及时提出，谢谢
