### ISSUE TITLE
安装在 my_plugins 目录，看起来没生效

### ISSUE THREAD

**Issue by OiCkilL** [AreCie/Apex_Tool#4]
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/613988/172103685-b02f8493-1c92-4ff5-8688-6c15b8ac7d3c.png">
插件装在 zhenxun_bot/my_plugins/Apex_Tool，WebUI 上是能看到的。不过关键字触发后就是报错

**Comment by AreCie** [comment]
> <img alt="image" width="1032" src="https://user-images.githubusercontent.com/613988/172103685-b02f8493-1c92-4ff5-8688-6c15b8ac7d3c.png">
> 
> 插件装在 zhenxun_bot/my_plugins/Apex_Tool，WebUI 上是能看到的。不过关键字触发后就是报错

这个报的读取Json文件的错，检查下json文件内容格式对不。。。

**Comment by 46516044** [comment]
这个报错一般是网页访问出错，看看api那个正不正确
