### ISSUE TITLE
无法生效

### ISSUE THREAD

**Issue by shabeeeeeee** [AreCie/Apex_Tool#5]
在按照使用方法安装后加载失败
![VLB07$SP)8H( 6D5PXL(O5R](https://user-images.githubusercontent.com/103305866/172549727-ad3f39a5-c4f1-423b-bef5-730986a5d931.png)
![0H`8B2A)DLVBTVZW(8ZI0%Y](https://user-images.githubusercontent.com/103305866/172549730-b843c5aa-e991-42ee-bd1e-03cf3471d223.png)
![{_%X 2EJNU3YG9$DK`{RV%C](https://user-images.githubusercontent.com/103305866/172549733-b236ff31-b98c-42c7-abf2-443f420bc488.png)

![IMG_20220608_172907](https://user-images.githubusercontent.com/103305866/172585055-d4b588af-3eb5-4512-9f9a-8e8bc7dddf31.jpg)

**Comment by quanquan1014** [comment]
> 在按照使用方法安装后加载失败 ![VLB07$SP)8H( 6D5PXL(O5R](https://user-images.githubusercontent.com/103305866/172549727-ad3f39a5-c4f1-423b-bef5-730986a5d931.png) ![0H8B2A)DLVBTVZW(8ZI0%Y](https://user-images.githubusercontent.com/103305866/172549730-b843c5aa-e991-42ee-bd1e-03cf3471d223.png) ![{_%X 2EJNU3YG9$DK{RV%C](https://user-images.githubusercontent.com/103305866/172549733-b236ff31-b98c-42c7-abf2-443f420bc488.png)
> 
> ![IMG_20220608_172907](https://user-images.githubusercontent.com/103305866/172585055-d4b588af-3eb5-4512-9f9a-8e8bc7dddf31.jpg)

安装 requests

**Comment by quanquan1014** [comment]
#2

**Comment by AreCie** [comment]
> 在按照使用方法安装后加载失败 ![VLB07$SP)8H( 6D5PXL(O5R](https://user-images.githubusercontent.com/103305866/172549727-ad3f39a5-c4f1-423b-bef5-730986a5d931.png) ![0H8B2A)DLVBTVZW(8ZI0%Y](https://user-images.githubusercontent.com/103305866/172549730-b843c5aa-e991-42ee-bd1e-03cf3471d223.png) ![{_%X 2EJNU3YG9$DK{RV%C](https://user-images.githubusercontent.com/103305866/172549733-b236ff31-b98c-42c7-abf2-443f420bc488.png)
> 
> ![IMG_20220608_172907](https://user-images.githubusercontent.com/103305866/172585055-d4b588af-3eb5-4512-9f9a-8e8bc7dddf31.jpg)

安装下缺失的引用【requests】

**Comment by shabeeeeeee** [comment]
> #2
感谢大佬回复 已解决

**Comment by shabeeeeeee** [comment]
> > 在按照使用方法安装后加载失败 ![VLB07$SP)8H( 6D5PXL(O5R](https://user-images.githubusercontent.com/103305866/172549727-ad3f39a5-c4f1-423b-bef5-730986a5d931.png) ![0H8B2A)DLVBTVZW(8ZI0%Y](https://user-images.githubusercontent.com/103305866/172549730-b843c5aa-e991-42ee-bd1e-03cf3471d223.png) ![{_%X 2EJNU3YG9$DK{RV%C](https://user-images.githubusercontent.com/103305866/172549733-b236ff31-b98c-42c7-abf2-443f420bc488.png)
> > ![IMG_20220608_172907](https://user-images.githubusercontent.com/103305866/172585055-d4b588af-3eb5-4512-9f9a-8e8bc7dddf31.jpg)
> 
> 安装下缺失的引用【requests】
感谢大佬回复 已解决
