### ISSUE TITLE
为啥用不了呢,是我配置不对吗

### ISSUE THREAD

**Issue by Rememem** [AreCie/Apex_Tool#6]
![a查询失败](https://user-images.githubusercontent.com/58849545/180108418-12d562ed-1866-4d89-859a-396ef82c7d44.jpg)

**Comment by AreCie** [comment]
> ![一个查询失败](https://user-images.githubusercontent.com/58849545/180108418-12d562ed-1866-4d89-859a-396ef82c7d44.jpg)

看了下，是新模式的数据导致的，稍后我修复下上传

**Comment by AreCie** [comment]
> ![a查询失败](https://user-images.githubusercontent.com/58849545/180108418-12d562ed-1866-4d89-859a-396ef82c7d44.jpg)

代码已修复，只替换【__init__.py】文件就可以了，或者在原本49-50中间插入
``if data == "ltm":
            continue
``
