### ISSUE TITLE
打开全局代理就不能使用这个插件

### ISSUE THREAD

**Issue by 15220526** [AreCie/Apex_Tool#8]
该怎么解决这个问题因为有的其他插件需要用到代理,但是开了代理这个插件就无法使用了
![QQ截图20220817102428](https://user-images.githubusercontent.com/106159640/185020854-f978fb71-0e48-4dcb-954a-bf25d744f63e.jpg)

**Comment by AreCie** [comment]
> 该怎么解决这个问题因为有的其他插件需要用到代理,但是开了代理这个插件就无法使用了 ![QQ截图20220817102428](https://user-images.githubusercontent.com/106159640/185020854-f978fb71-0e48-4dcb-954a-bf25d744f63e.jpg)

是 Windows 还是 Linux，我这边复现一下，看错误应该是空类型错误

**Comment by AreCie** [comment]
> 该怎么解决这个问题因为有的其他插件需要用到代理,但是开了代理这个插件就无法使用了 ![QQ截图20220817102428](https://user-images.githubusercontent.com/106159640/185020854-f978fb71-0e48-4dcb-954a-bf25d744f63e.jpg)

不用了，定位到原因了，马上修复

**Comment by 15220526** [comment]
是windows的

**Comment by AreCie** [comment]
> 是windows的

好

**Comment by AreCie** [comment]
> 是windows的

你可以先试下在代理状态下直接请求这个Url，看看需要多久响应``https://api.mozambiquehe.re/crafting?auth=把文字换成自己申请的Token``

**Comment by 15220526** [comment]
直接就可以搜出来一秒不到

**Comment by AreCie** [comment]
> 直接就可以搜出来一秒不到

好的

**Comment by AreCie** [comment]
> 该怎么解决这个问题因为有的其他插件需要用到代理,但是开了代理这个插件就无法使用了 ![QQ截图20220817102428](https://user-images.githubusercontent.com/106159640/185020854-f978fb71-0e48-4dcb-954a-bf25d744f63e.jpg)

请求的是哪一个指令?``a地图``么？

**Comment by 15220526** [comment]
是a查询a

**Comment by AreCie** [comment]
> 是a查询a

好，我这边复现出来了，正在修复

**Comment by AreCie** [comment]
> 该怎么解决这个问题因为有的其他插件需要用到代理,但是开了代理这个插件就无法使用了 ![QQ截图20220817102428](https://user-images.githubusercontent.com/106159640/185020854-f978fb71-0e48-4dcb-954a-bf25d744f63e.jpg)

已修复，我这里本地Windows挂代理和不挂代理都试了，没再出现此类问题

**Comment by AreCie** [comment]
拉下最新代码文件``__init__.py`` ``utils.py``覆盖下，然后重启Bot，试试

**Comment by 15220526** [comment]
ok可以已经解决了

**Comment by AreCie** [comment]
> ok可以已经解决了

好的😃
