### ISSUE TITLE
报错 No module named 'services.log'

### ISSUE THREAD

**Issue by qianxuu** [AreCie/Apex_Tool#9]
一开始是报错没有 services，我就 pip 装了一下，然后报错这个了
```
08-18 08:49:22 [ERROR] nonebot | Failed to import "Apex_Tool"
Traceback (most recent call last):
  File "/usr/local/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
  File "/usr/local/lib/python3.9/dist-packages/nb_cli/handlers/deploy.py", line 20, in run_bot
    module = importlib.import_module(module_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "./bot.py", line 26, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/load.py", line 119, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/load.py", line 53, in load_all_plugins
    return manager.load_all_plugins()
  File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/manager.py", line 172, in load_all_plugins
    return set(
  File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/manager.py", line 173, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/manager.py", line 148, in load_plugin
    module = importlib.import_module(
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "./src/plugins/Apex_Tool/__init__.py", line 5, in <module>
    from services.log import logger
ModuleNotFoundError: No module named 'services.log'
```

**Comment by AreCie** [comment]
> 一开始是报错没有 services，我就 pip 装了一下，然后报错这个了
> 
> ```
> 08-18 08:49:22 [ERROR] nonebot | Failed to import "Apex_Tool"
> Traceback (most recent call last):
>   File "/usr/local/bin/nb", line 8, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1130, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1055, in main
>     rv = self.invoke(ctx)
>   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1657, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1404, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 760, in invoke
>     return __callback(*args, **kwargs)
>   File "/usr/local/lib/python3.9/dist-packages/nb_cli/commands/main.py", line 30, in run
>     run_bot(file, app)
>   File "/usr/local/lib/python3.9/dist-packages/nb_cli/handlers/deploy.py", line 20, in run_bot
>     module = importlib.import_module(module_name)
>   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 790, in exec_module
>   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
>   File "./bot.py", line 26, in <module>
>     nonebot.load_from_toml("pyproject.toml")
>   File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/load.py", line 119, in load_from_toml
>     return load_all_plugins(plugins, plugin_dirs)
>   File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/load.py", line 53, in load_all_plugins
>     return manager.load_all_plugins()
>   File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/manager.py", line 172, in load_all_plugins
>     return set(
>   File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/manager.py", line 173, in <genexpr>
>     filter(None, (self.load_plugin(name) for name in self.available_plugins))
> > File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/manager.py", line 148, in load_plugin
>     module = importlib.import_module(
>   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
>   File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/manager.py", line 237, in exec_module
>     super().exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 790, in exec_module
>   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
>   File "./src/plugins/Apex_Tool/__init__.py", line 5, in <module>
>     from services.log import logger
> ModuleNotFoundError: No module named 'services.log'
> ```

安装下``logger``试试：

``` shell
pip install logger -i https://pypi.tuna.tsinghua.edu.cn/simple #使用清华源安装logger
```

这个错挺离谱的...``logger``是用来记录日志的，这个模块应该默认是有的...真寻Bot插件里有许多地方都用到这个了......

**Comment by qianxuu** [comment]
> > 一开始是报错没有 services，我就 pip 装了一下，然后报错这个了
> > ```
> > 08-18 08:49:22 [ERROR] nonebot | Failed to import "Apex_Tool"
> > Traceback (most recent call last):
> >   File "/usr/local/bin/nb", line 8, in <module>
> >     sys.exit(main())
> >   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1130, in __call__
> >     return self.main(*args, **kwargs)
> >   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1055, in main
> >     rv = self.invoke(ctx)
> >   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1657, in invoke
> >     return _process_result(sub_ctx.command.invoke(sub_ctx))
> >   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1404, in invoke
> >     return ctx.invoke(self.callback, **ctx.params)
> >   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 760, in invoke
> >     return __callback(*args, **kwargs)
> >   File "/usr/local/lib/python3.9/dist-packages/nb_cli/commands/main.py", line 30, in run
> >     run_bot(file, app)
> >   File "/usr/local/lib/python3.9/dist-packages/nb_cli/handlers/deploy.py", line 20, in run_bot
> >     module = importlib.import_module(module_name)
> >   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
> >     return _bootstrap._gcd_import(name[level:], package, level)
> >   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
> >   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
> >   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
> >   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
> >   File "<frozen importlib._bootstrap_external>", line 790, in exec_module
> >   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
> >   File "./bot.py", line 26, in <module>
> >     nonebot.load_from_toml("pyproject.toml")
> >   File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/load.py", line 119, in load_from_toml
> >     return load_all_plugins(plugins, plugin_dirs)
> >   File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/load.py", line 53, in load_all_plugins
> >     return manager.load_all_plugins()
> >   File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/manager.py", line 172, in load_all_plugins
> >     return set(
> >   File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/manager.py", line 173, in <genexpr>
> >     filter(None, (self.load_plugin(name) for name in self.available_plugins))
> > > File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/manager.py", line 148, in load_plugin
> >     module = importlib.import_module(
> >   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
> >     return _bootstrap._gcd_import(name[level:], package, level)
> >   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
> >   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
> >   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
> >   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
> >   File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/manager.py", line 237, in exec_module
> >     super().exec_module(module)
> >   File "<frozen importlib._bootstrap_external>", line 790, in exec_module
> >   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
> >   File "./src/plugins/Apex_Tool/__init__.py", line 5, in <module>
> >     from services.log import logger
> > ModuleNotFoundError: No module named 'services.log'
> > ```
> 
> 安装下`logger`试试：
> 
> ```shell
> pip install logger -i https://pypi.tuna.tsinghua.edu.cn/simple #使用清华源安装logger
> ```
> 
> 这个错挺离谱的...`logger`是用来记录日志的，这个模块应该默认是有的...真寻Bot插件里有许多地方都用到这个了......

装了 logger 还是一样的报错，是需要依赖真寻吗，我是单独在 nonebot2 中使用的

**Comment by AreCie** [comment]
> > > 一开始是报错没有 services，我就 pip 装了一下，然后报错这个了
> > > ```
> > > 08-18 08:49:22 [ERROR] nonebot | Failed to import "Apex_Tool"
> > > Traceback (most recent call last):
> > >   File "/usr/local/bin/nb", line 8, in <module>
> > >     sys.exit(main())
> > >   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1130, in __call__
> > >     return self.main(*args, **kwargs)
> > >   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1055, in main
> > >     rv = self.invoke(ctx)
> > >   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1657, in invoke
> > >     return _process_result(sub_ctx.command.invoke(sub_ctx))
> > >   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1404, in invoke
> > >     return ctx.invoke(self.callback, **ctx.params)
> > >   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 760, in invoke
> > >     return __callback(*args, **kwargs)
> > >   File "/usr/local/lib/python3.9/dist-packages/nb_cli/commands/main.py", line 30, in run
> > >     run_bot(file, app)
> > >   File "/usr/local/lib/python3.9/dist-packages/nb_cli/handlers/deploy.py", line 20, in run_bot
> > >     module = importlib.import_module(module_name)
> > >   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
> > >     return _bootstrap._gcd_import(name[level:], package, level)
> > >   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
> > >   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
> > >   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
> > >   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
> > >   File "<frozen importlib._bootstrap_external>", line 790, in exec_module
> > >   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
> > >   File "./bot.py", line 26, in <module>
> > >     nonebot.load_from_toml("pyproject.toml")
> > >   File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/load.py", line 119, in load_from_toml
> > >     return load_all_plugins(plugins, plugin_dirs)
> > >   File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/load.py", line 53, in load_all_plugins
> > >     return manager.load_all_plugins()
> > >   File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/manager.py", line 172, in load_all_plugins
> > >     return set(
> > >   File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/manager.py", line 173, in <genexpr>
> > >     filter(None, (self.load_plugin(name) for name in self.available_plugins))
> > > > File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/manager.py", line 148, in load_plugin
> > >     module = importlib.import_module(
> > >   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
> > >     return _bootstrap._gcd_import(name[level:], package, level)
> > >   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
> > >   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
> > >   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
> > >   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
> > >   File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/manager.py", line 237, in exec_module
> > >     super().exec_module(module)
> > >   File "<frozen importlib._bootstrap_external>", line 790, in exec_module
> > >   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
> > >   File "./src/plugins/Apex_Tool/__init__.py", line 5, in <module>
> > >     from services.log import logger
> > > ModuleNotFoundError: No module named 'services.log'
> > > ```
> > 
> > 
> > 安装下`logger`试试：
> > ```shell
> > pip install logger -i https://pypi.tuna.tsinghua.edu.cn/simple #使用清华源安装logger
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这个错挺离谱的...`logger`是用来记录日志的，这个模块应该默认是有的...真寻Bot插件里有许多地方都用到这个了......
> 
> 装了 logger 还是一样的报错，是需要依赖真寻吗，我是单独在 nonebot2 中使用的

这个插件是针对真寻Bot做的，``nonebot2``中没试过。。。

**Comment by qianxuu** [comment]
> > > > 一开始是报错没有 services，我就 pip 装了一下，然后报错这个了
> > > > ```
> > > > 08-18 08:49:22 [ERROR] nonebot | Failed to import "Apex_Tool"
> > > > Traceback (most recent call last):
> > > >   File "/usr/local/bin/nb", line 8, in <module>
> > > >     sys.exit(main())
> > > >   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1130, in __call__
> > > >     return self.main(*args, **kwargs)
> > > >   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1055, in main
> > > >     rv = self.invoke(ctx)
> > > >   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1657, in invoke
> > > >     return _process_result(sub_ctx.command.invoke(sub_ctx))
> > > >   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1404, in invoke
> > > >     return ctx.invoke(self.callback, **ctx.params)
> > > >   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 760, in invoke
> > > >     return __callback(*args, **kwargs)
> > > >   File "/usr/local/lib/python3.9/dist-packages/nb_cli/commands/main.py", line 30, in run
> > > >     run_bot(file, app)
> > > >   File "/usr/local/lib/python3.9/dist-packages/nb_cli/handlers/deploy.py", line 20, in run_bot
> > > >     module = importlib.import_module(module_name)
> > > >   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
> > > >     return _bootstrap._gcd_import(name[level:], package, level)
> > > >   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
> > > >   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
> > > >   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
> > > >   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
> > > >   File "<frozen importlib._bootstrap_external>", line 790, in exec_module
> > > >   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
> > > >   File "./bot.py", line 26, in <module>
> > > >     nonebot.load_from_toml("pyproject.toml")
> > > >   File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/load.py", line 119, in load_from_toml
> > > >     return load_all_plugins(plugins, plugin_dirs)
> > > >   File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/load.py", line 53, in load_all_plugins
> > > >     return manager.load_all_plugins()
> > > >   File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/manager.py", line 172, in load_all_plugins
> > > >     return set(
> > > >   File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/manager.py", line 173, in <genexpr>
> > > >     filter(None, (self.load_plugin(name) for name in self.available_plugins))
> > > > > File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/manager.py", line 148, in load_plugin
> > > >     module = importlib.import_module(
> > > >   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
> > > >     return _bootstrap._gcd_import(name[level:], package, level)
> > > >   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
> > > >   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
> > > >   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
> > > >   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
> > > >   File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/manager.py", line 237, in exec_module
> > > >     super().exec_module(module)
> > > >   File "<frozen importlib._bootstrap_external>", line 790, in exec_module
> > > >   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
> > > >   File "./src/plugins/Apex_Tool/__init__.py", line 5, in <module>
> > > >     from services.log import logger
> > > > ModuleNotFoundError: No module named 'services.log'
> > > > ```
> > > 
> > > 
> > > 安装下`logger`试试：
> > > ```shell
> > > pip install logger -i https://pypi.tuna.tsinghua.edu.cn/simple #使用清华源安装logger
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 这个错挺离谱的...`logger`是用来记录日志的，这个模块应该默认是有的...真寻Bot插件里有许多地方都用到这个了......
> > 
> > 
> > 装了 logger 还是一样的报错，是需要依赖真寻吗，我是单独在 nonebot2 中使用的
> 
> 这个插件是针对真寻Bot做的，`nonebot2`中没试过。。。

好吧（

**Comment by qianxuu** [comment]
从真寻仓库里面搬了些文件过来，补了一些依赖，导入不报错了，期间因为 gino 依赖的 SQLAlchemy 版本太低导致我别的插件报错了，我还魔改了一下 gino（
![image](https://user-images.githubusercontent.com/62287903/185276419-761e8594-b97c-415f-9ce0-0615125b136b.png)

**Comment by AreCie** [comment]
> 从真寻仓库里面帮了些文件过来，补了一些依赖，导入不报错了，期间因为 gino 依赖的 SQLAlchemy 版本太低导致我别的插件报错了，我还魔改了一下 gino（ ![image](https://user-images.githubusercontent.com/62287903/185276419-761e8594-b97c-415f-9ce0-0615125b136b.png)

大佬太强了ヾ(≧▽≦*)o

**Comment by qianxuu** [comment]
> > 从真寻仓库里面帮了些文件过来，补了一些依赖，导入不报错了，期间因为 gino 依赖的 SQLAlchemy 版本太低导致我别的插件报错了，我还魔改了一下 gino（ ![image](https://user-images.githubusercontent.com/62287903/185276419-761e8594-b97c-415f-9ce0-0615125b136b.png)
> 
> 大佬太强了ヾ(≧▽≦*)o

![image](https://user-images.githubusercontent.com/62287903/185276942-4bb830c7-47cf-414e-9977-f9fa73a8e42c.png)
草（

**Comment by AreCie** [comment]
> > > 从真寻仓库里面帮了些文件过来，补了一些依赖，导入不报错了，期间因为 gino 依赖的 SQLAlchemy 版本太低导致我别的插件报错了，我还魔改了一下 gino（ ![image](https://user-images.githubusercontent.com/62287903/185276419-761e8594-b97c-415f-9ce0-0615125b136b.png)
> > 
> > 
> > 大佬太强了ヾ(≧▽≦*)o
> 
> ![image](https://user-images.githubusercontent.com/62287903/185276942-4bb830c7-47cf-414e-9977-f9fa73a8e42c.png) 草（

看来需要改一下路径代码，应该是两个框架获取的路径有所差别导致的(

**Comment by qianxuu** [comment]
> > > > 从真寻仓库里面帮了些文件过来，补了一些依赖，导入不报错了，期间因为 gino 依赖的 SQLAlchemy 版本太低导致我别的插件报错了，我还魔改了一下 gino（ ![image](https://user-images.githubusercontent.com/62287903/185276419-761e8594-b97c-415f-9ce0-0615125b136b.png)
> > > 
> > > 
> > > 大佬太强了ヾ(≧▽≦*)o
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/62287903/185276942-4bb830c7-47cf-414e-9977-f9fa73a8e42c.png) 草（
> 
> 看来需要改一下路径代码，应该是两个框架获取的路径有所差别导致的(

![image](https://user-images.githubusercontent.com/62287903/185282843-d2d26e25-2e17-4964-9675-f5cbaecb8c42.png)
试了一下改成绝对路径，一切正常了🎉

**Comment by AreCie** [comment]
> > > > > 从真寻仓库里面帮了些文件过来，补了一些依赖，导入不报错了，期间因为 gino 依赖的 SQLAlchemy 版本太低导致我别的插件报错了，我还魔改了一下 gino（ ![image](https://user-images.githubusercontent.com/62287903/185276419-761e8594-b97c-415f-9ce0-0615125b136b.png)
> > > > 
> > > > 
> > > > 大佬太强了ヾ(≧▽≦*)o
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/62287903/185276942-4bb830c7-47cf-414e-9977-f9fa73a8e42c.png) 草（
> > 
> > 
> > 看来需要改一下路径代码，应该是两个框架获取的路径有所差别导致的(
> 
> ![image](https://user-images.githubusercontent.com/62287903/185282843-d2d26e25-2e17-4964-9675-f5cbaecb8c42.png) 试了一下改成绝对路径，一切正常了🎉

好耶q(≧▽≦q)

**Comment by H-xiaoH** [comment]
> 从真寻仓库里面搬了些文件过来，补了一些依赖，导入不报错了，期间因为 gino 依赖的 SQLAlchemy 版本太低导致我别的插件报错了，我还魔改了一下 gino（ ![image](https://user-images.githubusercontent.com/62287903/185276419-761e8594-b97c-415f-9ce0-0615125b136b.png)

我也遇到了 `ModuleNotFoundError: No module named 'services.log'` 的问题……
由于我 `绪山真寻 Bot` 装不上所以想问问需要怎么修改来应用到 `NoneBot2` 里面。

**Comment by ANGJustinl** [comment]
![image](https://user-images.githubusercontent.com/96008766/197333329-df376792-b717-4fb3-b71e-b7680ec321ec.png)
这个是真寻bot里的插件直接引用没有依赖？

**Comment by ANGJustinl** [comment]
![image](https://user-images.githubusercontent.com/96008766/197333361-5df6bdd8-f615-4214-bbdb-4068894c2039.png)
